 # Python Skills
 ### By Zachary Galante 

# Indexing and using operations on elements of a list
## Using an f-string as well to print the variable within the line of text

In [4]:
sales=[100.72,63.29,44.00,12.95,1067.50,100.00,9.83,55.92,72.89,550.75]
thirdSales = print(f" Every Third Sale: {sales[::3]}")
thirdsales = [100.72, 12.95, 9.83, 550.75]
totalSales = sum(thirdsales)
print(totalSales)


 Every Third Sale: [100.72, 12.95, 9.83, 550.75]
674.25


# List Comprehensions
## Using list comprehensions to calculate the relative frequency of the list of numbers

In [2]:
nums = list(range(1,11))
sum_of_nums = sum(nums)
rel_freq = [num/sum_of_nums for num in nums]
rel_freq

[0.01818181818181818,
 0.03636363636363636,
 0.05454545454545454,
 0.07272727272727272,
 0.09090909090909091,
 0.10909090909090909,
 0.12727272727272726,
 0.14545454545454545,
 0.16363636363636364,
 0.18181818181818182]

# Using Hash Tables to perform word count on a text file 
### The output of the code is written at the bottom of the cell as a comment

In [ ]:
with open('aliceInWonderland.txt', 'r') as file:
    text = file.read().strip() 
word_counts, duration_in_seconds = word_count_via_dicts(text)
word_freq_list = [[v,k] for k,v in word_counts.items()]
word_freq_list.sort(reverse=True) 

print(f"The most frequent word is        '{word_freq_list[0][1]}' with a frequency of {word_freq_list[0][0]}") 
print(f"The second most frequent word is '{word_freq_list[1][1]}' with a frequency of {word_freq_list[1][0]}"
      
#OUTPUT
#The most frequent word is        'the' with a frequency of 1791
#The second most frequent word is 'and' with a frequency of 881

# Numpy 


## Exploring the functions of the Numpy library, such as the np.concatenate() function

In [5]:
import numpy as np 
a0 = [1,2,3,4,5,6,7,8]
a1 = np.array(a0)
a2 = [9,10,11,12,13,14,15]
a3 = np.array(a2)
np.concatenate((a1,a3), axis = 0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## Using fancy indexing to mainpulate the columns of a Numpy array 

In [11]:
import numpy as np 
arr  = np.arange(9).reshape(3,3)
print(f" Array before fancy indexing:\n {arr}")
b = arr[:,[0,2,1]]
print(f"Array after fancy indexing:\n {b}")

 Array before fancy indexing:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Array after fancy indexing:
 [[0 2 1]
 [3 5 4]
 [6 8 7]]


## Calculating Euclidean distance between two points 

In [13]:
import numpy as np 
import pandas as pd 
arr = [3,5,6,7,8]
arr1 = [6,8,2,4,9]
new_arr = np.array(arr)
new_arr1  = np.array(arr1)
total = np.power(new_arr - new_arr1,2)
c = np.sum(total)
print(f'The Euclidean Distance between the two points is: {c}')

The Euclidean Distance between the two points is: 44


# Pandas

## Creating a basic Dataframe from three lists of values, and then creating the dataframe using a dictionary style based approach 

### Once the Dataframe is initialized I am removing the missing values, with the .dropna() function while also making use of the "thresh" keyword.

In [20]:
import pandas as pd
import numpy as np
ser = pd.Series(['Zach', 'Anthony', None, 'Andrew', 'Kelly', 'Nate', None, 'Lou', 'Paul', None, 'Rosemary'])
age = pd.Series([19,44,None,45,43,8,None,75,74,None,72])
ser2  = pd.Series(['Medway', 'Hyde Park', None , 'Somerville','Somerville', 'Dedham', None , 'Hyde Park','Medway', None , 'Medway'])
df1 = pd.DataFrame({"Family Member Name": ser,
                   'Age': age,
                   'Town': ser2})
ser2  = pd.Series(['Medway', 'Hyde Park', None , 'Somerville','Somerville', 'Dedham', None , 'Hyde Park','Medway', None , 'Medway'])
df1
df1.dropna(thresh = 2)

Family Member Name   Age        Town
0                Zach  19.0      Medway
1             Anthony  44.0   Hyde Park
3              Andrew  45.0  Somerville
4               Kelly  43.0  Somerville
5                Nate   8.0      Dedham
7                 Lou  75.0   Hyde Park
8                Paul  74.0      Medway
10           Rosemary  72.0      Medway