 # Python Skills
 ### By Zachary Galante 
 

# Indexing and using operations on elements of a list
## Using an f-string as well to print the variable within the line of text

In [4]:
sales=[100.72,63.29,44.00,12.95,1067.50,100.00,9.83,55.92,72.89,550.75]
thirdSales = print(f" Every Third Sale: {sales[::3]}")
thirdsales = [100.72, 12.95, 9.83, 550.75]
totalSales = sum(thirdsales)
print(totalSales)


 Every Third Sale: [100.72, 12.95, 9.83, 550.75]
674.25


# List Comprehensions
## Using list comprehensions to calculate the relative frequency of the list of numbers

In [2]:
nums = list(range(1,11))
sum_of_nums = sum(nums)
rel_freq = [num/sum_of_nums for num in nums]
rel_freq

[0.01818181818181818,
 0.03636363636363636,
 0.05454545454545454,
 0.07272727272727272,
 0.09090909090909091,
 0.10909090909090909,
 0.12727272727272726,
 0.14545454545454545,
 0.16363636363636364,
 0.18181818181818182]

# Using Hash Tables to perform word count on a text file 
### The output of the code is written at the bottom of the cell as a comment

In [ ]:
with open('aliceInWonderland.txt', 'r') as file:
    text = file.read().strip() 
word_counts, duration_in_seconds = word_count_via_dicts(text)
word_freq_list = [[v,k] for k,v in word_counts.items()]
word_freq_list.sort(reverse=True) 

print(f"The most frequent word is        '{word_freq_list[0][1]}' with a frequency of {word_freq_list[0][0]}") 
print(f"The second most frequent word is '{word_freq_list[1][1]}' with a frequency of {word_freq_list[1][0]}"
      
#OUTPUT
#The most frequent word is        'the' with a frequency of 1791
#The second most frequent word is 'and' with a frequency of 881

# Numpy 


## Exploring the functions of the Numpy library, such as the np.concatenate() function

In [5]:
import numpy as np 
a0 = [1,2,3,4,5,6,7,8]
a1 = np.array(a0)
a2 = [9,10,11,12,13,14,15]
a3 = np.array(a2)
np.concatenate((a1,a3), axis = 0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## Fancy Indexing
### Using fancy indexing to manipulate the columns of an array

In [11]:
import numpy as np 
arr  = np.arange(9).reshape(3,3)
print(f" Array before fancy indexing:\n {arr}")
b = arr[:,[0,2,1]]
print(f"Array after fancy indexing:\n {b}")

 Array before fancy indexing:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Array after fancy indexing:
 [[0 2 1]
 [3 5 4]
 [6 8 7]]


## Euclidean Distance
### Using numpy arrays, I am finding the Euclidean distance between two points

In [13]:
import numpy as np 
import pandas as pd 
arr = [3,5,6,7,8]
arr1 = [6,8,2,4,9]
new_arr = np.array(arr)
new_arr1  = np.array(arr1)
total = np.power(new_arr - new_arr1,2)
c = np.sum(total)
print(f'The Euclidean Distance between the two points is: {c}')

The Euclidean Distance between the two points is: 44


# Pandas

## Creating a Dataframe

### Once the Dataframe is initialized I am removing the missing values, with the .dropna() function while also making use of the "thresh" keyword.

In [20]:
import pandas as pd
import numpy as np
ser = pd.Series(['Zach', 'Anthony', None, 'Andrew', 'Kelly', 'Nate', None, 'Lou', 'Paul', None, 'Rosemary'])
age = pd.Series([19,44,None,45,43,8,None,75,74,None,72])
ser2  = pd.Series(['Medway', 'Hyde Park', None , 'Somerville','Somerville', 'Dedham', None , 'Hyde Park','Medway', None , 'Medway'])
df1 = pd.DataFrame({"Family Member Name": ser,
                   'Age': age,
                   'Town': ser2})
ser2  = pd.Series(['Medway', 'Hyde Park', None , 'Somerville','Somerville', 'Dedham', None , 'Hyde Park','Medway', None , 'Medway'])
df1
df1.dropna(thresh = 2)

Family Member Name   Age        Town
0                Zach  19.0      Medway
1             Anthony  44.0   Hyde Park
3              Andrew  45.0  Somerville
4               Kelly  43.0  Somerville
5                Nate   8.0      Dedham
7                 Lou  75.0   Hyde Park
8                Paul  74.0      Medway
10           Rosemary  72.0      Medway

## apply() function 
### Here, I am using the apply() function to take the mean of each row and column to then return back a row and column of the results in each example below

In [38]:
import numpy as np
import pandas as pd
df1 = pd.DataFrame(np.arange(20).reshape(4,5), columns = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'], index = ['Bobby', 'Zach','Anthony', 'Chase'])
print(df1)
rw = df1.apply(lambda row: row.mean(), axis = 0)
print(f" Returns the mean of each column in a row form\n{rw}") #Will return the mean of each column in a row.
cl = df1.apply(lambda col: col.mean(), axis =1)
print(f"Returns the mean of each row in a column form\n{cl}") #Will return the mean of each row in a new column form

         Monday  Tuesday  Wednesday  Thursday  Friday
Bobby         0        1          2         3       4
Zach          5        6          7         8       9
Anthony      10       11         12        13      14
Chase        15       16         17        18      19
 Returns the mean of each column in a row form
Monday        7.5
Tuesday       8.5
Wednesday     9.5
Thursday     10.5
Friday       11.5
dtype: float64
Returns the mean of each row in a column form
Bobby       2.0
Zach        7.0
Anthony    12.0
Chase      17.0
dtype: float64


## Groupby() function 
### After creating a Dataframe from a dictionary, I am using the groupby function to find the sum for each city

In [82]:
import numpy as np
import pandas as pd 
tech_companies = pd.DataFrame({'Company Name':['Apple','Microsoft','IBM','Tesla','Facebook','Oculus', 'Sony'],
                             'City':['California', 'Washington', 'New York', 'California', 'Massachusetts', 'New York', 'Massachusetts'],
                             '2019 Price': [23,45,77,12,34,55,87],
                             '2020 Price': [26,76,100,104,44,23,19]})

print(f"Original Dataframe:\n {tech_companies}")  
groups = tech_companies.groupby('City').sum()
print(f"Grouped Dataframe by city and calculating the sum:\n {groups}")



Original Dataframe:
   Company Name           City  2019 Price  2020 Price
0        Apple     California          23          26
1    Microsoft     Washington          45          76
2          IBM       New York          77         100
3        Tesla     California          12         104
4     Facebook  Massachusetts          34          44
5       Oculus       New York          55          23
6         Sony  Massachusetts          87          19
Grouped Dataframe by city and calculating the sum:
                2019 Price  2020 Price
City                                 
California             35         130
Massachusetts         121          63
New York              132         123
Washington             45          76


## Filling missing values with groupby()
### Here I am making an NFL Dataframe with the teams points scored each week and then calculating the average score each week which is then added to the Dataframe and is used to fill any missing values.

In [134]:
import pandas as pd
import numpy as np
f_scores = pd.DataFrame({'Week 1':[45,21,10,None,35,38,24,None,],
                        'Week 2':[21,None,24,34,None,18,None,27],
                        'Week 3':[None,14,35,24,32,21,18,24],
                        'Week 4':[0, 21,42,24,17,24,35,42],
                        'Divison':['NFC North','NFC North','NFC North','NFC North','AFC East','AFC East','AFC East','AFC East']},
                       index = ['Packers','Bears','Vikings','Lions','Patriots','Jets','Bills','Dolphins'])

#div_avg = f_scores.groupby('Divison').mean()
wk_avg = f_scores.apply(lambda col: col.mean() if col.name in ['Week 1','Week 2','Week 3','Week 4'] else ("None"),  axis = 0)
# Getting a row back of the average of each column for each week
new_row = pd.DataFrame([wk_avg], index = ["Average Score"])
# Creating a new row which is going to be initialized as a Dataframe to be concatenated to the original Dataframe.
f1_scores = pd.concat([f_scores,new_row])
# Adding the new Dataframe to the orginal to make one Dataframe.
f1_scores
f1_scores.fillna(wk_avg)
# Replacing any missing values with the Average score for the week.

Week 1  Week 2  Week 3  Week 4    Divison
Packers        45.000000    21.0    24.0   0.000  NFC North
Bears          21.000000    24.8    14.0  21.000  NFC North
Vikings        10.000000    24.0    35.0  42.000  NFC North
Lions          28.833333    34.0    24.0  24.000  NFC North
Patriots       35.000000    24.8    32.0  17.000   AFC East
Jets           38.000000    18.0    21.0  24.000   AFC East
Bills          24.000000    24.8    18.0  35.000   AFC East
Dolphins       28.833333    27.0    24.0  42.000   AFC East
Average Score  28.833333    24.8    24.0  25.625       None